name: Deploy FastAPI App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development

jobs:
  configure-aws:
    uses: ./.github/workflows/configure-aws.yml
    with:
      aws_region: us-east-1
      role_arn: arn:aws:iam::908027422461:role/TG-GithubActionsPipelineRole

  deploy:
    needs: configure-aws
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy FastAPI App
        run: |
          cdk deploy --app="python3 app.py" --require-approval=never --verbose
